version: "3.8"
services:
    # Mysql database container
    db:
        image: mysql
        container_name: db_mysql_laravel
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        networks:
            - tutorial

    # phpmyadmin container
    phpmyadmin:
        image: phpmyadmin
        container_name: tutorial_phpmyadmin
        restart: always
        depends_on:
            - db
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
        networks:
            - tutorial

    #  apache project container
    www:
        build: 
            context: .
            dockerfile : ./php/Dockerfile
        container_name: tutorial_symfony
        ports:
          - "8741:80"
        volumes:
            - .:/var/www/html
        restart: always
        networks:
            - tutorial

networks:
    tutorial:

volumes:
    db-data: